name: libgit2
description: A Dart FFI binding for libgit2
version: 0.0.1
homepage: https://github.com/maks/dart_libgit2

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  ffigen: ^4.1.3



ffigen:
  name: "libgit2"
  output: "lib/src/libgit2_generated_bindings.dart"
  headers:
    entry-points:
      - "/usr/include/git2.h"
  llvm-path:
    - "/usr/lib/llvm-13"
  structs:
    rename:
      "_(.*)": "$1_"
    member-rename:
      ".*":
        "_(.*)": "$1_"
